### PR TITLE
Comments

### PR DESCRIPTION
**Pull request by techmoves**
in this file we change this : 👍 

- [x] No Linters error

- [x] add coments

- [x] add likes

- [x] add popup

- [x] fetch api

- [x] Proper documentation

### CODE REVIEW

**Review by wolterbwambale — APPROVED** [review]
**### Status:Approved** 🟢 
@techmoves   congratulation 💯  for the great milestone move,
you can now merge your project.
cheers and happy coding.

**Comment by emmiiorji** [comment]
Hi @techmoves and Team, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

<div align='center'>

</div>

You have submitted a pull request with an incorrect work flow. In the course of developing the project, you must have given reviews to each other and merge your feature branches into the dev branch. However, this pull request  should have been opened from the **dev** branch into the **main** branch and include all the changes. Check [this article](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/code-review/articles/code_review_flow_group_projects.md) for more information.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by techmoves** [comment]
hi [emmiiorji](https://github.com/emmiiorji) 

this the lates PR :     https://github.com/wolterbwambale/javascriptCapstone/pull/27

**Comment by emmiiorji** [comment]
Hi @techmoves

Your submission is supposed to follow gitflow. This means that since your project is assumed to have been done with the development phase and ready for production, your pull request should be from the dev branch to main branch.

**Pull request merged**
